test_dictionary = [{
  "id": "t3_vq3n6u",
  "parsedId": "vq3n6u",
  "url": "https://www.reddit.com/r/PMBuddy/comments/vq3n6u/rpmbuddy_lounge/",
  "username": "rush86999",
  "title": "r/PMBuddy Lounge",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "A place for members of r/PMBuddy to chat with each other",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;A place for members of &lt;a href=\"/r/PMBuddy\"&gt;r/PMBuddy&lt;/a&gt; to chat with each other&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 23,
  "flair": None,
  "upVotes": 3,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2022-07-02T23:07:53.000Z",
  "scrapedAt": "2024-02-10T13:48:15.627Z",
  "dataType": "post"
},
{
  "id": "t3_1amx485",
  "parsedId": "1amx485",
  "url": "https://www.reddit.com/r/PMBuddy/comments/1amx485/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-09T20:00:34.000Z",
  "scrapedAt": "2024-02-10T13:48:16.031Z",
  "dataType": "post"
},
{
  "id": "t3_125hzyn",
  "parsedId": "125hzyn",
  "url": "https://www.reddit.com/r/digital_marketing/comments/125hzyn/subreddit_moderation_concerning_ai_tools/",
  "username": "fedja",
  "title": "Subreddit moderation concerning AI tools",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "Hi everyone,\n\nAs I'm sure you've all noticed, digital marketing is turning itself inside out coming to terms with AI and how it impacts our work. Lately, I've seen a flood of AI \"tools\" being promoted that advertise AI solutions for this and that, from text to imagery, and more.\n\nFirst of all, this subreddit was created to exist as a watercooler safe space for digital marketers who don't have anyone in their company or circle of friends to discuss their professional challenges. And our 1st and most important rule is no solicitation. There are no sales pitches at the watercooler, and even actual advice is suspect the moment it's attached to *\"and this thing you can buy will solve your problems\"*.\n\nI'm happy to reconsider the above and tweak (minimally) this rule if the community has a different point of view (comment below), but for now, that's the state of things.\n\n# Now to the issue at hand\n\nI'd like to urge everyone to learn to use AI, as it's going to be an unavoidable tool in our arsenal going forward but to be weary about the deluge of tools that claim to perform miracles.\n\nThere are a handful of AIs good enough to use today (ChatGPT and Midjourney being well-known examples), as well as an absolute dumpster fire of front-end interfaces that query the aforementioned AIs via API. I've tried a dozen, and they rarely add significant value beyond what the core tools themselves do. If anything, they add a layer of obscurity on top of the query-response process, which isn't doing the user any favors.\n\nThe vast majority of these hastily cobbled tools won't exist in a year. Please consider the implications of giving your money, personal data, and work data to a platform that's only forwarding your content to a different API. Consider the implications of not having access to any of your history when the garage projects inevitably drown in the sea of indistinguishable competitors.\n\n&amp;#x200B;\n\nIn light of this, we'll take a stronger moderation approach to removing the promotion of derivative AI tools and promotion. We'll also begin to enforce a zero-tolerance approach to promotion that seeks to circumvent the automod tools, such as posts that appeal to PM for more info or mention links in bios.\n\n**This is a community for PEOPLE who share a passion and profession to talk to each other, and not a community where you're sold to.** If you'd like that, I'm sure you can find any number of digital marketing communities out there where you can read sales pitches and promos.\n\nAs always, if you have ANY comments about the above moderation direction, let me know. Please keep them on the community moderation topic, if you'd like to write a lengthy post about the direction of AI and have that discussion, do post it and PM me, we probably could use a sticky for that debate for a while.",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hi everyone,&lt;/p&gt;\n\n&lt;p&gt;As I&amp;#39;m sure you&amp;#39;ve all noticed, digital marketing is turning itself inside out coming to terms with AI and how it impacts our work. Lately, I&amp;#39;ve seen a flood of AI &amp;quot;tools&amp;quot; being promoted that advertise AI solutions for this and that, from text to imagery, and more.&lt;/p&gt;\n\n&lt;p&gt;First of all, this subreddit was created to exist as a watercooler safe space for digital marketers who don&amp;#39;t have anyone in their company or circle of friends to discuss their professional challenges. And our 1st and most important rule is no solicitation. There are no sales pitches at the watercooler, and even actual advice is suspect the moment it&amp;#39;s attached to &lt;em&gt;&amp;quot;and this thing you can buy will solve your problems&amp;quot;&lt;/em&gt;.&lt;/p&gt;\n\n&lt;p&gt;I&amp;#39;m happy to reconsider the above and tweak (minimally) this rule if the community has a different point of view (comment below), but for now, that&amp;#39;s the state of things.&lt;/p&gt;\n\n&lt;h1&gt;Now to the issue at hand&lt;/h1&gt;\n\n&lt;p&gt;I&amp;#39;d like to urge everyone to learn to use AI, as it&amp;#39;s going to be an unavoidable tool in our arsenal going forward but to be weary about the deluge of tools that claim to perform miracles.&lt;/p&gt;\n\n&lt;p&gt;There are a handful of AIs good enough to use today (ChatGPT and Midjourney being well-known examples), as well as an absolute dumpster fire of front-end interfaces that query the aforementioned AIs via API. I&amp;#39;ve tried a dozen, and they rarely add significant value beyond what the core tools themselves do. If anything, they add a layer of obscurity on top of the query-response process, which isn&amp;#39;t doing the user any favors.&lt;/p&gt;\n\n&lt;p&gt;The vast majority of these hastily cobbled tools won&amp;#39;t exist in a year. Please consider the implications of giving your money, personal data, and work data to a platform that&amp;#39;s only forwarding your content to a different API. Consider the implications of not having access to any of your history when the garage projects inevitably drown in the sea of indistinguishable competitors.&lt;/p&gt;\n\n&lt;p&gt;&amp;#x200B;&lt;/p&gt;\n\n&lt;p&gt;In light of this, we&amp;#39;ll take a stronger moderation approach to removing the promotion of derivative AI tools and promotion. We&amp;#39;ll also begin to enforce a zero-tolerance approach to promotion that seeks to circumvent the automod tools, such as posts that appeal to PM for more info or mention links in bios.&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;This is a community for PEOPLE who share a passion and profession to talk to each other, and not a community where you&amp;#39;re sold to.&lt;/strong&gt; If you&amp;#39;d like that, I&amp;#39;m sure you can find any number of digital marketing communities out there where you can read sales pitches and promos.&lt;/p&gt;\n\n&lt;p&gt;As always, if you have ANY comments about the above moderation direction, let me know. Please keep them on the community moderation topic, if you&amp;#39;d like to write a lengthy post about the direction of AI and have that discussion, do post it and PM me, we probably could use a sticky for that debate for a while.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 36,
  "flair": None,
  "upVotes": 73,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-03-29T09:03:58.000Z",
  "scrapedAt": "2024-02-10T13:48:16.159Z",
  "dataType": "post"
},
{
  "id": "t3_1aiq2cp",
  "parsedId": "1aiq2cp",
  "url": "https://www.reddit.com/r/PMBuddy/comments/1aiq2cp/week_77_e5_roles_and_responsibilities_of_an_ai/",
  "username": "sidsaladi",
  "title": "Week 77 - E5 - Roles and Responsibilities of an AI Product Manager",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "URL: https://open.substack.com/pub/sidsaladi/p/week-77-e5-roles-and-responsibilities?r=k22jq&amp;utm_campaign=post&amp;utm_medium=web\nThumbnail: https://b.thumbs.redditmedia.com/R6UdH7aYhsqyF5IK2OmAavl5PKkdVTqPVV8u2JowunQ.jpg\nImages:\n\thttps://external-preview.redd.it/1vVj-tooSQEVmBKYXkI1_zHZMuC90k-BxbkOzk0fCr8.jpg?auto=webp&amp;s=4054a3e551f64762f7d44effc214960def7472f9\n",
  "html": None,
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-04T15:14:09.000Z",
  "scrapedAt": "2024-02-10T13:48:16.478Z",
  "dataType": "post"
},
{
  "id": "t3_1ahcpp4",
  "parsedId": "1ahcpp4",
  "url": "https://www.reddit.com/r/PMBuddy/comments/1ahcpp4/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-02T20:00:36.000Z",
  "scrapedAt": "2024-02-10T13:48:16.640Z",
  "dataType": "post"
},
{
  "id": "t3_1an811e",
  "parsedId": "1an811e",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1an811e/how_we_helped_an_ecommerce_clothing_store_grow/",
  "username": "WizardOfEcommerce",
  "title": "How we helped an e-commerce clothing store grow from $20k per month to $100k per month.",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "Hello Redditors,\n\nIn this post, I will share our insights and case study on how we grew an e-commerce clothing brand.\n\nI will keep it as short and straightforward as possible. Hopefully, you can apply this to your e-commerce store.\n\n**THE SITUATION**\n\n70% of revenue came from returning customers.\n\nThey didn't know their target CPA numbers. When they advertised, their target CPA was $15\n\nThey didn't know their LTV numbers\n\nThey were advertising all the products that they had, and only a few were generating sales\n\nThey were testing 1-2 new ads a month, and for the most part, they ran the same creatives repeatedly for the last 3 months.\n\nThey didn't have any email flows to retain more customers, although 70% of their monthly revenue came from fan customers, which meant the products were really good.\n\n\n**WHAT DID WE DO TO GROW THIS BRAND?**\n\n\n1. We calculated all the numbers to set a clear target cost to acquire new customers\n2. Instead of advertising all the products, we found that most sales came from 5 dresses.\n\nSo, we set our focus only on those 5 dresses.\n\nYou don't need to advertise all of your products. All you need to focus on is your HERO product/offer.  This is one of the reasons why I see a lot of brands fail to figure out their Facebook ads. They try to advertise all the products. It's hard enough to figure out the best way to advertise one hero product that is responsible for most of your sales. \n\nFocus on all your ad creation attention on the HERO product/offer.\n\n3) New creatives - previously, I mentioned that they were testing 1-2 new ads a month.\n\nWell, we started our ad launch we 40 ads showcasing the dresses in multiple videos like:\n\n- dress time capsule hacks for summer  \n- 3 reasons why you will love this dress  \n- 3 reasons why I hate these dresses ( negative angles also work)\n- vlog day with my 3 favorite outfits for the summer.\n\n\n4) We simplified the ad account structure with just 2 campaigns\n\n- Campaign for women with multiple testing ad sets showcasing best-selling dresses  \n- Campaign to join their special email VIP list to grow their email list.\n\nAll the campaigns used complete BROAD targeting, no retargeting ad sets, no interests, and no lookalikes.\n\nWe let ads do the targeting.\n\nMultiple ads had a frequency close to 2.0, meaning those ads were already retargeting.\n\nI don't want to get to deep into this retargeting, targeting conversation, I have other posts about this. That explains the concept behind \"ads do the targeting\"\n\n5) Regarding the email - we built :  \n- New welcome flow -  \n- VIP Flow -  \n- Birthday flow -  \n- We miss your flow  \n- Cart abandonment flow.  \nBy building these flows, we let email and SMS focus on customer retention rather than running Facebook retargeting campaigns\n\nA month after doing this, 80% of monthly revenue came from new customers.\n\nWe grew to $ 60,000 per month, staying for three months while the brand sorted out its inventory and focused on developing new dresses for limited availability drops.\n\n**THE CURRENT SITUATION**\n\n* Currently,  this brand is doing $100k - $120k in monthly sales.\n* 60-65% of revenue comes from new customers\n* 35-40% comes from returning customers\n* The average AOV is $92.43\n* Our Cost to acquire new customers is $55\n* Our LTV is $180+ and growing\n* Every 6 weeks, we launch new dress drops planned for a year.\n* All of this is without any monthly discount campaigns, pure product.\n* We run a discount once every 4 months and generate around $280 - $300k in that period.\n* We still don't use retargeting campaigns.\n* Customer retention is being handled by email &amp; SMS.\n\n**THE NEXT STEPS**\n\n1. We are implementing a loyalty program where we will offer cashback after a certain amount of spend in the store that will be kept as store credit and can be used in the next purchase. This will incentivize people to come back and spend more, which will result in raising our LTV.\n2. Conquer new markets to grow to $300k monthly without sales campaigns. After a year, we can finally do that because we have a healthy profit margin and good customer retention.\n3. Develop new products that people love.\n\nThanks for reading.",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hello Redditors,&lt;/p&gt;\n\n&lt;p&gt;In this post, I will share our insights and case study on how we grew an e-commerce clothing brand.&lt;/p&gt;\n\n&lt;p&gt;I will keep it as short and straightforward as possible. Hopefully, you can apply this to your e-commerce store.&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;THE SITUATION&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;70% of revenue came from returning customers.&lt;/p&gt;\n\n&lt;p&gt;They didn&amp;#39;t know their target CPA numbers. When they advertised, their target CPA was $15&lt;/p&gt;\n\n&lt;p&gt;They didn&amp;#39;t know their LTV numbers&lt;/p&gt;\n\n&lt;p&gt;They were advertising all the products that they had, and only a few were generating sales&lt;/p&gt;\n\n&lt;p&gt;They were testing 1-2 new ads a month, and for the most part, they ran the same creatives repeatedly for the last 3 months.&lt;/p&gt;\n\n&lt;p&gt;They didn&amp;#39;t have any email flows to retain more customers, although 70% of their monthly revenue came from fan customers, which meant the products were really good.&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;WHAT DID WE DO TO GROW THIS BRAND?&lt;/strong&gt;&lt;/p&gt;\n\n&lt;ol&gt;\n&lt;li&gt;We calculated all the numbers to set a clear target cost to acquire new customers&lt;/li&gt;\n&lt;li&gt;Instead of advertising all the products, we found that most sales came from 5 dresses.&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;p&gt;So, we set our focus only on those 5 dresses.&lt;/p&gt;\n\n&lt;p&gt;You don&amp;#39;t need to advertise all of your products. All you need to focus on is your HERO product/offer.  This is one of the reasons why I see a lot of brands fail to figure out their Facebook ads. They try to advertise all the products. It&amp;#39;s hard enough to figure out the best way to advertise one hero product that is responsible for most of your sales. &lt;/p&gt;\n\n&lt;p&gt;Focus on all your ad creation attention on the HERO product/offer.&lt;/p&gt;\n\n&lt;p&gt;3) New creatives - previously, I mentioned that they were testing 1-2 new ads a month.&lt;/p&gt;\n\n&lt;p&gt;Well, we started our ad launch we 40 ads showcasing the dresses in multiple videos like:&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;dress time capsule hacks for summer&lt;br/&gt;&lt;/li&gt;\n&lt;li&gt;3 reasons why you will love this dress&lt;br/&gt;&lt;/li&gt;\n&lt;li&gt;3 reasons why I hate these dresses ( negative angles also work)&lt;/li&gt;\n&lt;li&gt;vlog day with my 3 favorite outfits for the summer.&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;4) We simplified the ad account structure with just 2 campaigns&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;Campaign for women with multiple testing ad sets showcasing best-selling dresses&lt;br/&gt;&lt;/li&gt;\n&lt;li&gt;Campaign to join their special email VIP list to grow their email list.&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;All the campaigns used complete BROAD targeting, no retargeting ad sets, no interests, and no lookalikes.&lt;/p&gt;\n\n&lt;p&gt;We let ads do the targeting.&lt;/p&gt;\n\n&lt;p&gt;Multiple ads had a frequency close to 2.0, meaning those ads were already retargeting.&lt;/p&gt;\n\n&lt;p&gt;I don&amp;#39;t want to get to deep into this retargeting, targeting conversation, I have other posts about this. That explains the concept behind &amp;quot;ads do the targeting&amp;quot;&lt;/p&gt;\n\n&lt;p&gt;5) Regarding the email - we built :&lt;br/&gt;\n- New welcome flow -&lt;br/&gt;\n- VIP Flow -&lt;br/&gt;\n- Birthday flow -&lt;br/&gt;\n- We miss your flow&lt;br/&gt;\n- Cart abandonment flow.&lt;br/&gt;\nBy building these flows, we let email and SMS focus on customer retention rather than running Facebook retargeting campaigns&lt;/p&gt;\n\n&lt;p&gt;A month after doing this, 80% of monthly revenue came from new customers.&lt;/p&gt;\n\n&lt;p&gt;We grew to $ 60,000 per month, staying for three months while the brand sorted out its inventory and focused on developing new dresses for limited availability drops.&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;THE CURRENT SITUATION&lt;/strong&gt;&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;Currently,  this brand is doing $100k - $120k in monthly sales.&lt;/li&gt;\n&lt;li&gt;60-65% of revenue comes from new customers&lt;/li&gt;\n&lt;li&gt;35-40% comes from returning customers&lt;/li&gt;\n&lt;li&gt;The average AOV is $92.43&lt;/li&gt;\n&lt;li&gt;Our Cost to acquire new customers is $55&lt;/li&gt;\n&lt;li&gt;Our LTV is $180+ and growing&lt;/li&gt;\n&lt;li&gt;Every 6 weeks, we launch new dress drops planned for a year.&lt;/li&gt;\n&lt;li&gt;All of this is without any monthly discount campaigns, pure product.&lt;/li&gt;\n&lt;li&gt;We run a discount once every 4 months and generate around $280 - $300k in that period.&lt;/li&gt;\n&lt;li&gt;We still don&amp;#39;t use retargeting campaigns.&lt;/li&gt;\n&lt;li&gt;Customer retention is being handled by email &amp;amp; SMS.&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;&lt;strong&gt;THE NEXT STEPS&lt;/strong&gt;&lt;/p&gt;\n\n&lt;ol&gt;\n&lt;li&gt;We are implementing a loyalty program where we will offer cashback after a certain amount of spend in the store that will be kept as store credit and can be used in the next purchase. This will incentivize people to come back and spend more, which will result in raising our LTV.&lt;/li&gt;\n&lt;li&gt;Conquer new markets to grow to $300k monthly without sales campaigns. After a year, we can finally do that because we have a healthy profit margin and good customer retention.&lt;/li&gt;\n&lt;li&gt;Develop new products that people love.&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;p&gt;Thanks for reading.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 4,
  "flair": None,
  "upVotes": 15,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-10T04:36:09.000Z",
  "scrapedAt": "2024-02-10T13:48:16.961Z",
  "dataType": "post"
},
{
  "id": "t3_1amw8f8",
  "parsedId": "1amw8f8",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1amw8f8/google_ads_are_getting_no_impressions_despite/",
  "username": "No_Competition268",
  "title": "Google Ads are getting no impressions despite high budget",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "Hi everyone,\n\nI have a Google Ads account for law office in NYC with a daily budget of $1,000 per day and I have the CPC limit to $300 per click yet there's no impressions at all\n\nI tested going from exact match to phrase match, and even broad match keywords to see if it was a search volume problem\n\nKeywords like \"Car accident lawyer\" are not getting impressions on phrase match or broad match even\n\nI initially had manual CPC but then changed to Maximize Conversions and Maximize Clicks to see if any of them would work (I kept it only about 1 day so this might be the problem)\n\nIdeally I would prefer to find a solution and keep using manual CPC so I can control the spend much better\n\nBut right now I'd like to just start getting impressions and clicks to get the ball rolling",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hi everyone,&lt;/p&gt;\n\n&lt;p&gt;I have a Google Ads account for law office in NYC with a daily budget of $1,000 per day and I have the CPC limit to $300 per click yet there&amp;#39;s no impressions at all&lt;/p&gt;\n\n&lt;p&gt;I tested going from exact match to phrase match, and even broad match keywords to see if it was a search volume problem&lt;/p&gt;\n\n&lt;p&gt;Keywords like &amp;quot;Car accident lawyer&amp;quot; are not getting impressions on phrase match or broad match even&lt;/p&gt;\n\n&lt;p&gt;I initially had manual CPC but then changed to Maximize Conversions and Maximize Clicks to see if any of them would work (I kept it only about 1 day so this might be the problem)&lt;/p&gt;\n\n&lt;p&gt;Ideally I would prefer to find a solution and keep using manual CPC so I can control the spend much better&lt;/p&gt;\n\n&lt;p&gt;But right now I&amp;#39;d like to just start getting impressions and clicks to get the ball rolling&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 4,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-09T19:22:22.000Z",
  "scrapedAt": "2024-02-10T13:48:17.069Z",
  "dataType": "post"
},
{
  "id": "t3_1an5090",
  "parsedId": "1an5090",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1an5090/need_help_on_how_to_create_this_specific_ig_story/",
  "username": "fallbrownies",
  "title": "Need help on how to create this specific IG story ad",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "Basically as title says.\n\nI’ve been seeing a lot of retail and fashion brands with ig story ads with a clickable CTA sticker in its second carousel. The first card is usually an image or video with a product tag or the original CTA shop now link but the second card is a sticker in the middle of the carousel. Usually this CTA sticker or feature has the brand ig profile picture, the brand name, a text, sometimes the follower count, and a shop now button. \n\nIs there a way for me to recreate this in Ads manager or is this an Advantage+ creative optimization? Thanks in advance!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Basically as title says.&lt;/p&gt;\n\n&lt;p&gt;I’ve been seeing a lot of retail and fashion brands with ig story ads with a clickable CTA sticker in its second carousel. The first card is usually an image or video with a product tag or the original CTA shop now link but the second card is a sticker in the middle of the carousel. Usually this CTA sticker or feature has the brand ig profile picture, the brand name, a text, sometimes the follower count, and a shop now button. &lt;/p&gt;\n\n&lt;p&gt;Is there a way for me to recreate this in Ads manager or is this an Advantage+ creative optimization? Thanks in advance!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": "Meta",
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-10T01:54:34.000Z",
  "scrapedAt": "2024-02-10T13:48:17.369Z",
  "dataType": "post"
},
{
  "id": "t3_1ag27f1",
  "parsedId": "1ag27f1",
  "url": "https://www.reddit.com/r/PMBuddy/comments/1ag27f1/folks_need_some_idea_how_you_guys_plan_ab_test/",
  "username": "Glass-Wolverine07",
  "title": "Folks, need some idea how you guys plan AB test hypothesis and priorities for the quarter and what tools you rely on.",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "",
  "html": "None",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-01T04:16:19.000Z",
  "scrapedAt": "2024-02-10T13:48:17.641Z",
  "dataType": "post"
},
{
  "id": "t3_1amvn8j",
  "parsedId": "1amvn8j",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1amvn8j/launching_my_first_google_ads_search_campaign/",
  "username": "sparkzz911",
  "title": "Launching My First Google Ads Search Campaign: Seeking Advice on Optimization Services - Are They Worth the Cost?",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "We are a tutoring company and are running our first google ads search campaign.  We have 2 branches that are completely different from one another, so we are running 2 different campaigns.\n\nWe set up the campaign using chat gpt 4 (headlines, keywords, snippets, everything essentially).  We are now about to start running them and looking to hire on upwork for them to look over the analytics every 2 weeks for the first month and then once a month following that. \n\n**We've narrowed it down to these candidates, and would love your opinion which is the best to hire:**\n\n&amp;#x200B;\n\nKP:\n\n3 hours per week for both campaigns \\~$453)\n\nOngoing monthly management \\~ $270\n\n&amp;#x200B;\n\nHK:\n\n10 hours per week for both campaigns $15010 hours\n\nMonthly review (Once a month) $150\n\n&amp;#x200B;\n\nAP:\n\n2 hours every 2 weeks for $200 to manage both campaigns\n\n&amp;#x200B;\n\nAL:\n\n3 hours per week  to manage both campaigns- $56 per week\n\nMonthly: $336\n\n&amp;#x200B;\n\nWhatever guidance you can give we would appreciate on who is best to hire!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;We are a tutoring company and are running our first google ads search campaign.  We have 2 branches that are completely different from one another, so we are running 2 different campaigns.&lt;/p&gt;\n\n&lt;p&gt;We set up the campaign using chat gpt 4 (headlines, keywords, snippets, everything essentially).  We are now about to start running them and looking to hire on upwork for them to look over the analytics every 2 weeks for the first month and then once a month following that. &lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;We&amp;#39;ve narrowed it down to these candidates, and would love your opinion which is the best to hire:&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;&amp;#x200B;&lt;/p&gt;\n\n&lt;p&gt;KP:&lt;/p&gt;\n\n&lt;p&gt;3 hours per week for both campaigns ~$453)&lt;/p&gt;\n\n&lt;p&gt;Ongoing monthly management ~ $270&lt;/p&gt;\n\n&lt;p&gt;&amp;#x200B;&lt;/p&gt;\n\n&lt;p&gt;HK:&lt;/p&gt;\n\n&lt;p&gt;10 hours per week for both campaigns $15010 hours&lt;/p&gt;\n\n&lt;p&gt;Monthly review (Once a month) $150&lt;/p&gt;\n\n&lt;p&gt;&amp;#x200B;&lt;/p&gt;\n\n&lt;p&gt;AP:&lt;/p&gt;\n\n&lt;p&gt;2 hours every 2 weeks for $200 to manage both campaigns&lt;/p&gt;\n\n&lt;p&gt;&amp;#x200B;&lt;/p&gt;\n\n&lt;p&gt;AL:&lt;/p&gt;\n\n&lt;p&gt;3 hours per week  to manage both campaigns- $56 per week&lt;/p&gt;\n\n&lt;p&gt;Monthly: $336&lt;/p&gt;\n\n&lt;p&gt;&amp;#x200B;&lt;/p&gt;\n\n&lt;p&gt;Whatever guidance you can give we would appreciate on who is best to hire!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 1,
  "flair": "Question",
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-09T18:57:02.000Z",
  "scrapedAt": "2024-02-10T13:48:17.782Z",
  "dataType": "post"
},
{
  "id": "t3_1abrdj1",
  "parsedId": "1abrdj1",
  "url": "https://www.reddit.com/r/PMBuddy/comments/1abrdj1/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-01-26T20:00:32.000Z",
  "scrapedAt": "2024-02-10T13:48:18.108Z",
  "dataType": "post"
},
{
  "id": "t3_1amhxt1",
  "parsedId": "1amhxt1",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1amhxt1/helping_reddit_family_in_ecommerce_today/",
  "username": "raphaelzandaya",
  "title": "Helping Reddit family in E-commerce today",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "Hey Guys,\n\nI havebeen running a digital agency for 5+ years and currently working with 50+ clients. I saw many entrepreneurs are facing problems in their startups so I am here to help you out\n\n&amp;#x200B;\n\ncomment below where you're stuck rightnow. I will try to respond ASAP\n\n&amp;#x200B;",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hey Guys,&lt;/p&gt;\n\n&lt;p&gt;I havebeen running a digital agency for 5+ years and currently working with 50+ clients. I saw many entrepreneurs are facing problems in their startups so I am here to help you out&lt;/p&gt;\n\n&lt;p&gt;&amp;#x200B;&lt;/p&gt;\n\n&lt;p&gt;comment below where you&amp;#39;re stuck rightnow. I will try to respond ASAP&lt;/p&gt;\n\n&lt;p&gt;&amp;#x200B;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 11,
  "flair": None,
  "upVotes": 6,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-09T06:39:05.000Z",
  "scrapedAt": "2024-02-10T13:48:18.266Z",
  "dataType": "post"
},
{
  "id": "t3_1amg4f9",
  "parsedId": "1amg4f9",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1amg4f9/experienced_digital_marketer_seeking/",
  "username": "ireneblessing",
  "title": "Experienced Digital Marketer Seeking Opportunities in Google and Facebook Ads Agency!",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "Hey everyone!\r  \n\r  \nI'm a seasoned digital marketer passionate about driving results through Google and Facebook ads. Having honed my skills through working with various clients on platforms like Upwork, I'm now eager to transition into a dynamic agency environment where I can collaborate with a team.\r  \n\r  \nAbout Me:  \nExperience: I've worked with various clients, managing campaigns across different industries.  \nSpecialization: My expertise lies in Google and Facebook ads, where I've consistently delivered impressive results.  \nPortfolio: I'm more than willing to share my portfolio showcasing successful campaigns and their tangible impact on businesses.  \nFull-time Availability: Ready to dive in full-time and contribute to the team's and our client's success.  \nAd Spend: Throughout my career, I've managed ad budgets exceeding USD 14 million, demonstrating my ability to handle large-scale campaigns effectively.  \nWhy I'm Seeking Agency Work:  \nWhile freelancing has its perks, working in isolation can be pretty solitary. I thrive in a collaborative environment where ideas can be bounced around, strategies can be refined through collective brainstorming, and victories can be celebrated as a team. Joining an agency is not just about finding a job; it's about finding a community of like-minded professionals with whom I can grow and succeed.  \nWhat I Bring to the Table:  \nProven track record of delivering ROI-driven campaigns.  \nStrategic thinking combined with a data-driven approach.  \nStrong communication skills, both in conveying ideas and analyzing campaign performance.  \nAdaptability to different client needs and industry landscapes.\n\n  \nA genuine passion for staying updated on the latest trends and technologies in digital marketing.  \nIf you're part of a Google or Facebook ads agency looking for a dedicated and results-oriented digital marketer, I'd love to connect! Please feel free to drop me a message or comment below, and let's talk about how we can collaborate to drive phenomenal results for your agency and its clients.  \nI look forward to hearing from you all and embarking on this exciting journey together!  \nCheers,  \nIrene",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hey everyone!&lt;/p&gt;\n\n&lt;p&gt;I&amp;#39;m a seasoned digital marketer passionate about driving results through Google and Facebook ads. Having honed my skills through working with various clients on platforms like Upwork, I&amp;#39;m now eager to transition into a dynamic agency environment where I can collaborate with a team.&lt;/p&gt;\n\n&lt;p&gt;About Me:&lt;br/&gt;\nExperience: I&amp;#39;ve worked with various clients, managing campaigns across different industries.&lt;br/&gt;\nSpecialization: My expertise lies in Google and Facebook ads, where I&amp;#39;ve consistently delivered impressive results.&lt;br/&gt;\nPortfolio: I&amp;#39;m more than willing to share my portfolio showcasing successful campaigns and their tangible impact on businesses.&lt;br/&gt;\nFull-time Availability: Ready to dive in full-time and contribute to the team&amp;#39;s and our client&amp;#39;s success.&lt;br/&gt;\nAd Spend: Throughout my career, I&amp;#39;ve managed ad budgets exceeding USD 14 million, demonstrating my ability to handle large-scale campaigns effectively.&lt;br/&gt;\nWhy I&amp;#39;m Seeking Agency Work:&lt;br/&gt;\nWhile freelancing has its perks, working in isolation can be pretty solitary. I thrive in a collaborative environment where ideas can be bounced around, strategies can be refined through collective brainstorming, and victories can be celebrated as a team. Joining an agency is not just about finding a job; it&amp;#39;s about finding a community of like-minded professionals with whom I can grow and succeed.&lt;br/&gt;\nWhat I Bring to the Table:&lt;br/&gt;\nProven track record of delivering ROI-driven campaigns.&lt;br/&gt;\nStrategic thinking combined with a data-driven approach.&lt;br/&gt;\nStrong communication skills, both in conveying ideas and analyzing campaign performance.&lt;br/&gt;\nAdaptability to different client needs and industry landscapes.&lt;/p&gt;\n\n&lt;p&gt;A genuine passion for staying updated on the latest trends and technologies in digital marketing.&lt;br/&gt;\nIf you&amp;#39;re part of a Google or Facebook ads agency looking for a dedicated and results-oriented digital marketer, I&amp;#39;d love to connect! Please feel free to drop me a message or comment below, and let&amp;#39;s talk about how we can collaborate to drive phenomenal results for your agency and its clients.&lt;br/&gt;\nI look forward to hearing from you all and embarking on this exciting journey together!&lt;br/&gt;\nCheers,&lt;br/&gt;\nIrene&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 4,
  "flair": None,
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-09T04:52:40.000Z",
  "scrapedAt": "2024-02-10T13:48:18.548Z",
  "dataType": "post"
},
{
  "id": "t3_19c5hqc",
  "parsedId": "19c5hqc",
  "url": "https://www.reddit.com/r/PMBuddy/comments/19c5hqc/week_75_prompt_engineering_basics_and_50_free/",
  "username": "sidsaladi",
  "title": "Week 75 - 🛠️ Prompt Engineering Basics and 50+ Free 🎁 Product Management Prompts 🚀",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "URL: https://open.substack.com/pub/sidsaladi/p/week-75-prompt-engineering-basics?r=k22jq&amp;utm_campaign=post&amp;utm_medium=web&amp;showWelcome=true\nThumbnail: https://b.thumbs.redditmedia.com/IRlDlDK2yLCtN_XwlIhJn8ggrvpp-tXLMlor6LTnZLg.jpg\nImages:\n\thttps://external-preview.redd.it/aQExi3AS-9oU15cz6B3yo6AIugR6Unps4dohoDfPABE.jpg?auto=webp&amp;s=b57891bf5c49a5edbd2afc2f8020ef632b2ed55c\n",
  "html": None,
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-01-21T15:14:33.000Z",
  "scrapedAt": "2024-02-10T13:48:18.733Z",
  "dataType": "post"
},
{
  "id": "t3_19as6v8",
  "parsedId": "19as6v8",
  "url": "https://www.reddit.com/r/PMBuddy/comments/19as6v8/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-01-19T20:00:33.000Z",
  "scrapedAt": "2024-02-10T13:48:18.958Z",
  "dataType": "post"
},
{
  "id": "t3_196ibio",
  "parsedId": "196ibio",
  "url": "https://www.reddit.com/r/PMBuddy/comments/196ibio/week_74_e2_basics_of_large_language_models_for/",
  "username": "sidsaladi",
  "title": "Week 74 - E2- Basics of Large Language Models for Product Managers 🤖",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "URL: https://open.substack.com/pub/sidsaladi/p/week-74-e2-basics-of-large-language?r=k22jq&amp;utm_campaign=post&amp;utm_medium=web\nThumbnail: https://b.thumbs.redditmedia.com/GHxk4HAYGVYKHrmxCE98R-WpNZbWeMlDqBm7T25hEts.jpg\nImages:\n\thttps://external-preview.redd.it/SDB71qz23wEKFcv0yTvgih6ZahEjAgnO5c8sB3CrT2I.jpg?auto=webp&amp;s=e60f8f74891d661a11ca15b7cb4cdaaf06f5ab2c\n",
  "html": None,
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-01-14T15:27:09.000Z",
  "scrapedAt": "2024-02-10T13:48:19.138Z",
  "dataType": "post"
},
{
  "id": "t3_19548ts",
  "parsedId": "19548ts",
  "url": "https://www.reddit.com/r/PMBuddy/comments/19548ts/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-01-12T20:00:35.000Z",
  "scrapedAt": "2024-02-10T13:48:19.365Z",
  "dataType": "post"
},
{
  "id": "t3_1am2wpu",
  "parsedId": "1am2wpu",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1am2wpu/tracking_form_fields/",
  "username": "Danger_Mouse8",
  "title": "Tracking form fields",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "We have a small form on our website with around ten fields consisting of manual input fields, drop downs and radio buttons. I’d like to know where people are dropping off on the form. How am I best doing this?",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;We have a small form on our website with around ten fields consisting of manual input fields, drop downs and radio buttons. I’d like to know where people are dropping off on the form. How am I best doing this?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 3,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T18:45:35.000Z",
  "scrapedAt": "2024-02-10T13:48:19.541Z",
  "dataType": "post"
},
{
  "id": "t3_190vxbr",
  "parsedId": "190vxbr",
  "url": "https://www.reddit.com/r/PMBuddy/comments/190vxbr/week_73_e1_introduction_to_general_ai_for_product/",
  "username": "sidsaladi",
  "title": "🤖 Week 73 - E1- Introduction to General AI for Product Managers 🤖",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "URL: https://open.substack.com/pub/sidsaladi/p/week-74-e1-introduction-to-general?r=k22jq&amp;utm_campaign=post&amp;utm_medium=web\nThumbnail: https://b.thumbs.redditmedia.com/emuA2vuSO6-p3DpizOMqxuMcafw8jgt_JuTdP2qHJQQ.jpg\nImages:\n\thttps://external-preview.redd.it/WEEJD9v9z2XZzf4y094OE25Ye5eK4omHD-Ne692pG8E.jpg?auto=webp&amp;s=dac2fbfd6a645096652d580d0722fa55ae2999bc\n",
  "html": None,
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-01-07T16:29:51.000Z",
  "scrapedAt": "2024-02-10T13:48:19.848Z",
  "dataType": "post"
},
{
  "id": "t3_1am1pj2",
  "parsedId": "1am1pj2",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1am1pj2/will_donate_to_charity_of_your_choice_for_your/",
  "username": "bestlist-dot-com",
  "title": "Will donate to charity of your choice for your marketing expertise.",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "Hi, I'm Tyler.   \nI'm working on a new product for marketers, and I'm looking to do some user tests with marketers to get some initial feedback.  \n  \nI'm willing to pay for your time, or I can donate to a charity of your choice. **It'll be roughly a 30 minute video call, and I'll pay $100.**  \n  \nInterested? Please DM me.  \nThank you.",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hi, I&amp;#39;m Tyler.&lt;br/&gt;\nI&amp;#39;m working on a new product for marketers, and I&amp;#39;m looking to do some user tests with marketers to get some initial feedback.  &lt;/p&gt;\n\n&lt;p&gt;I&amp;#39;m willing to pay for your time, or I can donate to a charity of your choice. &lt;strong&gt;It&amp;#39;ll be roughly a 30 minute video call, and I&amp;#39;ll pay $100.&lt;/strong&gt;  &lt;/p&gt;\n\n&lt;p&gt;Interested? Please DM me.&lt;br/&gt;\nThank you.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": "Question",
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T17:55:25.000Z",
  "scrapedAt": "2024-02-10T13:48:20.012Z",
  "dataType": "post"
},
{
  "id": "t3_18zfzmk",
  "parsedId": "18zfzmk",
  "url": "https://www.reddit.com/r/PMBuddy/comments/18zfzmk/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-01-05T20:00:31.000Z",
  "scrapedAt": "2024-02-10T13:48:20.271Z",
  "dataType": "post"
},
{
  "id": "t3_1alrq4k",
  "parsedId": "1alrq4k",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1alrq4k/how_important_is_the_comments_section/",
  "username": "Writing_Legal",
  "title": "How important is the comments section?",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "I’m building a sentiment analysis tool with open source resources and adding a language model layer to help with translating contextual written text into meaningful insights. I want to know how important the comments section is for product marketers and marketing teams and possibly even ask what tools you currently use to gather a sentiment analysis.",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I’m building a sentiment analysis tool with open source resources and adding a language model layer to help with translating contextual written text into meaningful insights. I want to know how important the comments section is for product marketers and marketing teams and possibly even ask what tools you currently use to gather a sentiment analysis.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": "Question",
  "upVotes": 4,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T09:16:31.000Z",
  "scrapedAt": "2024-02-10T13:48:20.431Z",
  "dataType": "post"
},
{
  "id": "t3_1alvlmk",
  "parsedId": "1alvlmk",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1alvlmk/legitimate_programs_launch_my_agency_digital_ceos/",
  "username": "julebox722",
  "title": "Legitimate Programs: Launch My Agency, Digital CEO's, Digital Leasing, CBI",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "Hello everyone!  I've been researching an online business for 2 months.  I wanted to ask if anyone has heard of \"Launch My Agency\", \"Digital CEO's (Josh Osbourne Digital Leasing\", and Christian Business Incubators.    \nI so much want to be involved in something.  I don't mind working, I want to work, don't expect it to be an overnight thing, but I just want it to be legitimate.  They all could be selling their programs and that's how they're making money.  I keep going back and forth with it.  Just curious if anyone is familiar with any of these.   \n",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hello everyone!  I&amp;#39;ve been researching an online business for 2 months.  I wanted to ask if anyone has heard of &amp;quot;Launch My Agency&amp;quot;, &amp;quot;Digital CEO&amp;#39;s (Josh Osbourne Digital Leasing&amp;quot;, and Christian Business Incubators.&lt;br/&gt;\nI so much want to be involved in something.  I don&amp;#39;t mind working, I want to work, don&amp;#39;t expect it to be an overnight thing, but I just want it to be legitimate.  They all could be selling their programs and that&amp;#39;s how they&amp;#39;re making money.  I keep going back and forth with it.  Just curious if anyone is familiar with any of these.   &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T13:23:07.000Z",
  "scrapedAt": "2024-02-10T13:48:20.665Z",
  "dataType": "post"
},
{
  "id": "t3_18ytsef",
  "parsedId": "18ytsef",
  "url": "https://www.reddit.com/r/PMBuddy/comments/18ytsef/week_72_top_9_product_management_predictions_for/",
  "username": "sidsaladi",
  "title": "Week 72 - Top 9 Product Management Predictions for 2024",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "URL: https://sidsaladi.substack.com/p/week-72-top-9-product-management\nThumbnail: https://b.thumbs.redditmedia.com/3jos72ZFyzvB7sWgYUuhUu69CGDOeqfH5ybXN4FmjFA.jpg\nImages:\n\thttps://external-preview.redd.it/a7j3r3UlwJeuLd2qorqX0sFegRC2VZK_xnzZyH8ENj8.jpg?auto=webp&amp;s=debe18221aa1e5948b3888aae49a885ff82145ff\n",
  "html": None,
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-01-05T01:08:13.000Z",
  "scrapedAt": "2024-02-10T13:48:20.910Z",
  "dataType": "post"
},
{
  "id": "t3_1alpt00",
  "parsedId": "1alpt00",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1alpt00/whats_the_best_way_to_grow_my_email_lists/",
  "username": "Saumya_88",
  "title": "What’s the best way to grow my email lists?",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "\r  \nI'm looking to expand my email subscriber list for my real estate business  and wanted to get this community's advice on the most effective strategies.\r  \n\r  \nRight now, my list is still small at just 500  subscribers. I know growing an engaged email list can really benefit a business by building meaningful relationships with potential customers.\r  \n\r  \nWhat has worked well for you when building up an email list? Are there any strategies I'm missing or things I should avoid? \r  \n\r  \n\r  \nThanks in advance!\r  \n",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I&amp;#39;m looking to expand my email subscriber list for my real estate business  and wanted to get this community&amp;#39;s advice on the most effective strategies.&lt;/p&gt;\n\n&lt;p&gt;Right now, my list is still small at just 500  subscribers. I know growing an engaged email list can really benefit a business by building meaningful relationships with potential customers.&lt;/p&gt;\n\n&lt;p&gt;What has worked well for you when building up an email list? Are there any strategies I&amp;#39;m missing or things I should avoid? &lt;/p&gt;\n\n&lt;p&gt;Thanks in advance!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 1,
  "flair": "Question",
  "upVotes": 3,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T06:59:57.000Z",
  "scrapedAt": "2024-02-10T13:48:22.002Z",
  "dataType": "post"
},
{
  "id": "t3_18tvxpq",
  "parsedId": "18tvxpq",
  "url": "https://www.reddit.com/r/PMBuddy/comments/18tvxpq/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-12-29T20:00:50.000Z",
  "scrapedAt": "2024-02-10T13:48:22.048Z",
  "dataType": "post"
},
{
  "id": "t3_18rjwe9",
  "parsedId": "18rjwe9",
  "url": "https://www.reddit.com/r/PMBuddy/comments/18rjwe9/week_71_product_strategy_vision_and_roadmap/",
  "username": "sidsaladi",
  "title": "Week 71 - Product Strategy, Vision and Roadmap",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "URL: https://open.substack.com/pub/sidsaladi/p/week-71-product-strategy-vision-and?r=k22jq&amp;utm_campaign=post&amp;utm_medium=web\nThumbnail: https://b.thumbs.redditmedia.com/Nkq4OMWUtES5l42dkAVJeK0Xzzk9Gi3t1yPTuuulrcY.jpg\nImages:\n\thttps://external-preview.redd.it/z2Fp8Q49vgfoFdaIp54wiiSHJKh7-E3B1_qcGsTf7aQ.jpg?auto=webp&amp;s=69f644b7b4a1b64b4c32896ecdcce5782ee6b15c\n",
  "html": None,
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-12-26T22:18:29.000Z",
  "scrapedAt": "2024-02-10T13:48:22.455Z",
  "dataType": "post"
},
{
  "id": "t3_18onj96",
  "parsedId": "18onj96",
  "url": "https://www.reddit.com/r/PMBuddy/comments/18onj96/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-12-22T20:00:30.000Z",
  "scrapedAt": "2024-02-10T13:48:22.541Z",
  "dataType": "post"
},
{
  "id": "t3_1alsh9t",
  "parsedId": "1alsh9t",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1alsh9t/homepage_takeover_advice/",
  "username": "Danger_Mouse8",
  "title": "Homepage 'takeover' advice",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "The company I work for is due to spend quite a bit of money in the next few months on paid social and programmatic display and a little bit of out of home. We're creating specific landing pages for this activity but my manager (head of marketing) also wants to make a connection with the ad activity and the homepage. \n\nAny advice on how we could do this without losing the essence of what the homepage is about and not diluting our overall message. We tend to just plaster things on the homepage for the sake of it and I often think why would a user care whether we're running this big campaign or not",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;The company I work for is due to spend quite a bit of money in the next few months on paid social and programmatic display and a little bit of out of home. We&amp;#39;re creating specific landing pages for this activity but my manager (head of marketing) also wants to make a connection with the ad activity and the homepage. &lt;/p&gt;\n\n&lt;p&gt;Any advice on how we could do this without losing the essence of what the homepage is about and not diluting our overall message. We tend to just plaster things on the homepage for the sake of it and I often think why would a user care whether we&amp;#39;re running this big campaign or not&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T10:10:57.000Z",
  "scrapedAt": "2024-02-10T13:48:22.982Z",
  "dataType": "post"
},
{
  "id": "t3_1aluzzx",
  "parsedId": "1aluzzx",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1aluzzx/ideas_needed/",
  "username": "vasanth310598",
  "title": "Ideas Needed",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "My company need to sell properties in out of city that was newly developing area, Give me some marketing ideas to sell the land using **Social media** and **Google Ads**",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;My company need to sell properties in out of city that was newly developing area, Give me some marketing ideas to sell the land using &lt;strong&gt;Social media&lt;/strong&gt; and &lt;strong&gt;Google Ads&lt;/strong&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": "Discussion",
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T12:51:21.000Z",
  "scrapedAt": "2024-02-10T13:48:23.051Z",
  "dataType": "post"
},
{
  "id": "t3_18j8tv3",
  "parsedId": "18j8tv3",
  "url": "https://www.reddit.com/r/PMBuddy/comments/18j8tv3/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-12-15T20:00:43.000Z",
  "scrapedAt": "2024-02-10T13:48:23.129Z",
  "dataType": "post"
},
{
  "id": "t3_18f6rbn",
  "parsedId": "18f6rbn",
  "url": "https://www.reddit.com/r/PMBuddy/comments/18f6rbn/httpssidsaladisubstackcompweek69succeedingwithstar/",
  "username": "sidsaladi",
  "title": "https://sidsaladi.substack.com/p/week-69-succeeding-with-startups?r=k22jq&amp;utm_campaign=post&amp;utm_medium=web",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "URL: https://open.substack.com/pub/sidsaladi/p/week-69-succeeding-with-startups?r=k22jq&amp;utm_campaign=post&amp;utm_medium=web\nThumbnail: https://b.thumbs.redditmedia.com/WaNb7JRveW3hnS8xY7jRfV-lqoyhWVI7p4T2o21nhuk.jpg\nImages:\n\thttps://external-preview.redd.it/-e87vmz4sRpWBVoeGcghAGhQ7BDMzwPj1zOUWvPbMpQ.jpg?auto=webp&amp;s=1b5ba6519896d7c74e9fc138242366a2f481738c\n",
  "html": None,
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-12-10T16:05:53.000Z",
  "scrapedAt": "2024-02-10T13:48:23.432Z",
  "dataType": "post"
},
{
  "id": "t3_1alvaby",
  "parsedId": "1alvaby",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1alvaby/sick_of_low_rattings_low_customers_contact_us_we/",
  "username": "justasTR",
  "title": "Sick Of Low Rattings Low Customers Contact Us We Will Help",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "Hello My Name is Justas Zalkauskas  \nWe are calling from TR Reselling.  \nWe Manage Everything for you. We Will Increase Your Revenue Your Clients And your Reviews on Google.  \nLow Google Reviews Ranks you further down from your Competition.  \nWe Will help you out with this With Google Ads Management.  \nContact Us  \nemail: trreselling@gmail.com  \nWhatsapp: +447716194376",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hello My Name is Justas Zalkauskas&lt;br/&gt;\nWe are calling from TR Reselling.&lt;br/&gt;\nWe Manage Everything for you. We Will Increase Your Revenue Your Clients And your Reviews on Google.&lt;br/&gt;\nLow Google Reviews Ranks you further down from your Competition.&lt;br/&gt;\nWe Will help you out with this With Google Ads Management.&lt;br/&gt;\nContact Us&lt;br/&gt;\nemail: &lt;a href=\"mailto:trreselling@gmail.com\"&gt;trreselling@gmail.com&lt;/a&gt;&lt;br/&gt;\nWhatsapp: +447716194376&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T13:06:45.000Z",
  "scrapedAt": "2024-02-10T13:48:23.526Z",
  "dataType": "post"
},
{
  "id": "t3_18dv887",
  "parsedId": "18dv887",
  "url": "https://www.reddit.com/r/PMBuddy/comments/18dv887/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-12-08T20:00:40.000Z",
  "scrapedAt": "2024-02-10T13:48:23.703Z",
  "dataType": "post"
},
{
  "id": "t3_1alheg3",
  "parsedId": "1alheg3",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1alheg3/is_this_black_hat/",
  "username": "Appropriate_Hair_813",
  "title": "Is this Black Hat?",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "I’m about a year into marketing and I think what I’ve been taught is black hat, but I’m not sure. Can anyone help me out here? I’ve left my last company and now that I’m applying to new jobs, I don’t see “*search arbitrage*,” anywhere. *Search arbitrage* is the kind of media buying I was doing on TikTok, it’s really spammy, we’d create these links, and landing pages, where we’d get paid off of clicks. Is this considered black hat marketing or affiliate (i wish i could upload a picture)? If so, I guess I have to remove it from my resume. We also made these click-baity ads for an app I later found out was malware.  Now that I’m gone and looking for more jobs in marketing, I’m starting to think I started off with the wrong company, because their markets were really niche. No applications match my experience in digital marketing. ",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I’m about a year into marketing and I think what I’ve been taught is black hat, but I’m not sure. Can anyone help me out here? I’ve left my last company and now that I’m applying to new jobs, I don’t see “&lt;em&gt;search arbitrage&lt;/em&gt;,” anywhere. &lt;em&gt;Search arbitrage&lt;/em&gt; is the kind of media buying I was doing on TikTok, it’s really spammy, we’d create these links, and landing pages, where we’d get paid off of clicks. Is this considered black hat marketing or affiliate (i wish i could upload a picture)? If so, I guess I have to remove it from my resume. We also made these click-baity ads for an app I later found out was malware.  Now that I’m gone and looking for more jobs in marketing, I’m starting to think I started off with the wrong company, because their markets were really niche. No applications match my experience in digital marketing. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 8,
  "flair": "Question",
  "upVotes": 6,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-07T23:41:51.000Z",
  "scrapedAt": "2024-02-10T13:48:24.014Z",
  "dataType": "post"
},
{
  "id": "t3_189xdfd",
  "parsedId": "189xdfd",
  "url": "https://www.reddit.com/r/PMBuddy/comments/189xdfd/week_68_how_to_manage_a_remote_product_team/",
  "username": "sidsaladi",
  "title": "Week 68 - 🏡 How to Manage a Remote Product Team 👨‍💻👩‍💻",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "URL: https://sidsaladi.substack.com/p/week-68-how-to-manage-a-remote-product\nThumbnail: https://b.thumbs.redditmedia.com/CWKtQ1bnLYON33NS651fpoIcYcqpmOOq6OyY5P4Lk-g.jpg\nImages:\n\thttps://external-preview.redd.it/7jx7F3ZtjhqP-Kx0hgF7J8sB_edYdVjPta55E614zqo.jpg?auto=webp&amp;s=86b1bfaae610b3ac6292da03b63e1175e3733801\n",
  "html": None,
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-12-03T16:42:37.000Z",
  "scrapedAt": "2024-02-10T13:48:24.201Z",
  "dataType": "post"
},
{
  "id": "t3_1alq0a9",
  "parsedId": "1alq0a9",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1alq0a9/can_you_please_suggest_free_email_marketing/",
  "username": "NoRepair1473",
  "title": "Can you Please suggest free email marketing platform that allows for cold emailing?",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "I tried to send emails to website owners for marketing using Mailchimp. But now, my account got suspended, and Mailchimp says. \"After a thorough review of your account, we've determined your campaigns are prospecting in nature, which is a violation of our Terms of Use.  It’s important to keep in mind that Mailchimp has specific requirements when it comes to permission for bulk emails. All contacts are required to go through an opt-in process using a verifiable medium whereby the individual grants you their direct permission to send them marketing emails.\" So what should I do now, Can you suggest any free email marketing platform that allows for cold emailing?",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I tried to send emails to website owners for marketing using Mailchimp. But now, my account got suspended, and Mailchimp says. &amp;quot;After a thorough review of your account, we&amp;#39;ve determined your campaigns are prospecting in nature, which is a violation of our Terms of Use.  It’s important to keep in mind that Mailchimp has specific requirements when it comes to permission for bulk emails. All contacts are required to go through an opt-in process using a verifiable medium whereby the individual grants you their direct permission to send them marketing emails.&amp;quot; So what should I do now, Can you suggest any free email marketing platform that allows for cold emailing?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 7,
  "flair": None,
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T07:13:33.000Z",
  "scrapedAt": "2024-02-10T13:48:24.230Z",
  "dataType": "post"
},
{
  "id": "t3_188kxi5",
  "parsedId": "188kxi5",
  "url": "https://www.reddit.com/r/PMBuddy/comments/188kxi5/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-12-01T20:00:45.000Z",
  "scrapedAt": "2024-02-10T13:48:24.581Z",
  "dataType": "post"
},
{
  "id": "t3_184ebr2",
  "parsedId": "184ebr2",
  "url": "https://www.reddit.com/r/PMBuddy/comments/184ebr2/week_67_how_to_run_a_design_sprint_the_ultimate/",
  "username": "sidsaladi",
  "title": "Week 67 - How to Run a Design Sprint: The Ultimate Guide for Product Managers + Free Templates",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "URL: https://open.substack.com/pub/sidsaladi/p/week-67-how-to-run-a-design-sprint?r=k22jq&amp;utm_medium=ios&amp;utm_campaign=post\nThumbnail: https://b.thumbs.redditmedia.com/GFjRooWv_tCoJJB-v9SPgRnoNkul3Ee0vm7awj9pEuU.jpg\nImages:\n\thttps://external-preview.redd.it/JaCyx5_fjQT-H275VNBOtBKo-UicA_iTbrGKPbHsACA.jpg?auto=webp&amp;s=2442ce564f70112416ae1724dafcb925b3684182\n",
  "html": None,
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-11-26T16:22:49.000Z",
  "scrapedAt": "2024-02-10T13:48:24.723Z",
  "dataType": "post"
},
{
  "id": "t3_1alpsza",
  "parsedId": "1alpsza",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1alpsza/whats_the_best_way_to_grow_my_email_lists/",
  "username": "Saumya_88",
  "title": "What’s the best way to grow my email lists?",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "\r  \nI'm looking to expand my email subscriber list for my real estate business  and wanted to get this community's advice on the most effective strategies.\r  \n\r  \nRight now, my list is still small at just 500  subscribers. I know growing an engaged email list can really benefit a business by building meaningful relationships with potential customers.\r  \n\r  \nWhat has worked well for you when building up an email list? Are there any strategies I'm missing or things I should avoid? \r  \n\r  \n\r  \nThanks in advance!\r  \n",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I&amp;#39;m looking to expand my email subscriber list for my real estate business  and wanted to get this community&amp;#39;s advice on the most effective strategies.&lt;/p&gt;\n\n&lt;p&gt;Right now, my list is still small at just 500  subscribers. I know growing an engaged email list can really benefit a business by building meaningful relationships with potential customers.&lt;/p&gt;\n\n&lt;p&gt;What has worked well for you when building up an email list? Are there any strategies I&amp;#39;m missing or things I should avoid? &lt;/p&gt;\n\n&lt;p&gt;Thanks in advance!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 1,
  "flair": "Question",
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T06:59:55.000Z",
  "scrapedAt": "2024-02-10T13:48:24.904Z",
  "dataType": "post"
},
{
  "id": "t3_1aloclp",
  "parsedId": "1aloclp",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1aloclp/tips_for_marketing_of_new_podcast/",
  "username": "LuckyFall6205",
  "title": "Tips for Marketing of New Podcast",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "I met a senior journalist at a B2B meeting, introduced by my dad. He's a script writer and content creator for documentaries, aged 62, seeking advice on better podcast marketing. \n\nI suggested using Spotify Advertising Manager, Google Ads, Meta Ads, etc. \n\nDespite being new to podcast marketing and more focused on content design and media buying, I felt a bit out of my element. Any additional tips would be appreciated!\n\nThe topic of podcast is [The focus on issues relevant to people's lives and society as a whole]",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I met a senior journalist at a B2B meeting, introduced by my dad. He&amp;#39;s a script writer and content creator for documentaries, aged 62, seeking advice on better podcast marketing. &lt;/p&gt;\n\n&lt;p&gt;I suggested using Spotify Advertising Manager, Google Ads, Meta Ads, etc. &lt;/p&gt;\n\n&lt;p&gt;Despite being new to podcast marketing and more focused on content design and media buying, I felt a bit out of my element. Any additional tips would be appreciated!&lt;/p&gt;\n\n&lt;p&gt;The topic of podcast is [The focus on issues relevant to people&amp;#39;s lives and society as a whole]&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 1,
  "flair": "Discussion",
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T05:29:48.000Z",
  "scrapedAt": "2024-02-10T13:48:25.243Z",
  "dataType": "post"
},
{
  "id": "t3_1830n3d",
  "parsedId": "1830n3d",
  "url": "https://www.reddit.com/r/PMBuddy/comments/1830n3d/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-11-24T20:00:36.000Z",
  "scrapedAt": "2024-02-10T13:48:25.318Z",
  "dataType": "post"
},
{
  "id": "t3_1ali8n7",
  "parsedId": "1ali8n7",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1ali8n7/social_media_intern_that_cant_post/",
  "username": "jj_hyyh",
  "title": "Social media intern that can’t post?",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "I just got an internship at a pr agency as a social media intern. I was told during my interview that I would be posting reels and stuff. I was looking for that type of experience anyways because I want more experience posting and having control of social media accounts. My 1st day comes and apparently I’m not allowed access to the account 💀 what kind of social media intern isn’t given access to the social media platforms?? Is this normal??",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I just got an internship at a pr agency as a social media intern. I was told during my interview that I would be posting reels and stuff. I was looking for that type of experience anyways because I want more experience posting and having control of social media accounts. My 1st day comes and apparently I’m not allowed access to the account 💀 what kind of social media intern isn’t given access to the social media platforms?? Is this normal??&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 3,
  "flair": "Discussion",
  "upVotes": 2,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-08T00:18:28.000Z",
  "scrapedAt": "2024-02-10T13:48:25.435Z",
  "dataType": "post"
},
{
  "id": "t3_17z140j",
  "parsedId": "17z140j",
  "url": "https://www.reddit.com/r/PMBuddy/comments/17z140j/week_66_why_product_managers_make_great_ceos_and/",
  "username": "sidsaladi",
  "title": "Week 66 - Why Product Managers Make Great CEOs 👨‍💼👩‍💼 and 7 Famous Examples Who Did 🚀",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "URL: https://sidsaladi.substack.com/p/week-66-why-product-managers-make\nThumbnail: https://b.thumbs.redditmedia.com/9wydnRdRXbbc5IFbHPMNZdajgDrsVZccTXkODMhB5jQ.jpg\nImages:\n\thttps://external-preview.redd.it/fK-64jrCsmAF25z2RirgkuOq1TyUCTxpVEjdT4TnolY.jpg?auto=webp&amp;s=eb7c27cdf3b6146a81142db763d1a518d9c2c8ea\n",
  "html": None,
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 0,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-11-19T16:40:38.000Z",
  "scrapedAt": "2024-02-10T13:48:25.886Z",
  "dataType": "post"
},
{
  "id": "t3_17xnmk5",
  "parsedId": "17xnmk5",
  "url": "https://www.reddit.com/r/PMBuddy/comments/17xnmk5/new_members_intro/",
  "username": "rush86999",
  "title": "New Members Intro",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "If you’re new to the community, introduce yourself!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;If you’re new to the community, introduce yourself!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-11-17T20:00:36.000Z",
  "scrapedAt": "2024-02-10T13:48:25.957Z",
  "dataType": "post"
},
{
  "id": "t3_1al1lll",
  "parsedId": "1al1lll",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1al1lll/is_this_a_fair_assessment/",
  "username": "reginapinsley",
  "title": "Is this a fair assessment?",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "I’ve recently started interviewing for Brand Strategy roles. One of the companies reached out with this assessment:\n\nYou are tasked with building a YouTube channel for the brand. Research the market and come up with a clear strategy for the YouTube channel. You should clearly identify content direction, references and the first 20 videos to make.  \n\nYou must submit a 10-slide plan that captures the following:\n1. YouTube strategy\n2. Plan to build a distinctive brand using YT\n3. Milestones and metrics for the first year\n\n\nMy thoughts:\n- this is very specific\n- are they looking to steal my work?\n- this is unpaid\n- only 24 hours for all of this\n- i provided them with my portfolio which includes multiple strategy decks, so is this even something that’s required?\n\nI’ll appreciate all perspectives. Thanks!",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I’ve recently started interviewing for Brand Strategy roles. One of the companies reached out with this assessment:&lt;/p&gt;\n\n&lt;p&gt;You are tasked with building a YouTube channel for the brand. Research the market and come up with a clear strategy for the YouTube channel. You should clearly identify content direction, references and the first 20 videos to make.  &lt;/p&gt;\n\n&lt;p&gt;You must submit a 10-slide plan that captures the following:\n1. YouTube strategy\n2. Plan to build a distinctive brand using YT\n3. Milestones and metrics for the first year&lt;/p&gt;\n\n&lt;p&gt;My thoughts:\n- this is very specific\n- are they looking to steal my work?\n- this is unpaid\n- only 24 hours for all of this\n- i provided them with my portfolio which includes multiple strategy decks, so is this even something that’s required?&lt;/p&gt;\n\n&lt;p&gt;I’ll appreciate all perspectives. Thanks!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 3,
  "flair": "Question",
  "upVotes": 5,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-07T12:16:57.000Z",
  "scrapedAt": "2024-02-10T13:48:26.023Z",
  "dataType": "post"
},
{
  "id": "t3_17to0wp",
  "parsedId": "17to0wp",
  "url": "https://www.reddit.com/r/PMBuddy/comments/17to0wp/week_65_the_psyche_of_todays_b2c_buyer_unraveling/",
  "username": "sidsaladi",
  "title": "Week 65 - 🧐 The Psyche of Today's B2C Buyer: Unraveling the Secrets of Their Purchasing Decisions",
  "communityName": "r/PMBuddy",
  "parsedCommunityName": "PMBuddy",
  "body": "URL: https://open.substack.com/pub/sidsaladi/p/week-66-the-psyche-of-todays-b2c?r=k22jq&amp;utm_campaign=post&amp;utm_medium=web\nThumbnail: https://b.thumbs.redditmedia.com/97FjZKJwDONq0-5MBu2LGp0izr2cvLaB5VKoFcqANUk.jpg\nImages:\n\thttps://external-preview.redd.it/Su8QGiOZnXVt3jwa4Y6JrOgPmX_i1P3ieZ0gcd_XCzg.jpg?auto=webp&amp;s=b6972ab99ae78b3ea094f0b0eca4351b19d5ca02\n",
  "html": None,
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2023-11-12T16:40:57.000Z",
  "scrapedAt": "2024-02-10T13:48:26.543Z",
  "dataType": "post"
},
{
  "id": "t3_1alblvs",
  "parsedId": "1alblvs",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1alblvs/what_would_you_do/",
  "username": "lolquallelol",
  "title": "What would YOU do?",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "Hey, I'm curious. If you do for example recruiting ads, would you just use an exciting headline and benefits (I'll write in the instagram caption which position I'm looking for exactly.) or would you do Method 2 by writing the position in the creative?\nThe first method has the benefit that it won't look like an ad and also has less text. What would you do?",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hey, I&amp;#39;m curious. If you do for example recruiting ads, would you just use an exciting headline and benefits (I&amp;#39;ll write in the instagram caption which position I&amp;#39;m looking for exactly.) or would you do Method 2 by writing the position in the creative?\nThe first method has the benefit that it won&amp;#39;t look like an ad and also has less text. What would you do?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 2,
  "flair": None,
  "upVotes": 1,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-07T19:40:32.000Z",
  "scrapedAt": "2024-02-10T13:48:26.657Z",
  "dataType": "post"
},
{
  "id": "t3_1al3hxq",
  "parsedId": "1al3hxq",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1al3hxq/ogilvy_on_advertising_was_mind_blowingly_good/",
  "username": "Key-Purpose-8948",
  "title": "Ogilvy on Advertising was mind blowing-ly good. Apply these key concepts now.",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "'𝐖𝐡𝐞𝐧 𝐲𝐨𝐮 𝐡𝐚𝐯𝐞 𝐰𝐫𝐢𝐭𝐭𝐞𝐧 𝐲𝐨𝐮𝐫 𝐡𝐞𝐚𝐝𝐥𝐢𝐧𝐞, 𝐲𝐨𝐮 𝐡𝐚𝐯𝐞 𝐬𝐩𝐞𝐧𝐭 𝐞𝐢𝐠𝐡𝐭𝐲 𝐜𝐞𝐧𝐭𝐬 𝐨𝐮𝐭 𝐨𝐟 𝐲𝐨𝐮𝐫 𝐝𝐨𝐥𝐥𝐚𝐫' - David Ogilvy\n\nFor context, I've been fairly new to the advertising niche, having just fully committed the past year to learning how to run ads regularly on social media platforms. That said, the book nerd in me came up with a list of 50 advertising books to read - and this was the first one I picked up at a local library.\n\nWhile I encourage newbies &amp; even experts who could use a refresher to thoroughly read and take notes from the book as the most effective method of learning, here are 3 key takeaways that I now use as a checklist:\n\n1. 𝐎𝐧 𝐂𝐫𝐚𝐟𝐭𝐢𝐧𝐠 𝐄𝐟𝐟𝐞𝐜𝐭𝐢𝐯𝐞 𝐀𝐝𝐯𝐞𝐫𝐭𝐢𝐬𝐢𝐧𝐠 𝐇𝐞𝐚𝐝𝐥𝐢𝐧𝐞𝐬:\n\n\\- The most successful headlines promise a benefit to the reader.\n\n\\- Headlines containing news elements are consistently effective.\n\n\\- It is advisable to almost always include the brand name in the headline.\n\n\\- A headline comprising approximately 10 words tends to have better sales impact.\n\n2. 𝐎𝐧 𝐒𝐭𝐮𝐝𝐲𝐢𝐧𝐠 𝐭𝐡𝐞 𝐏𝐫𝐨𝐝𝐮𝐜𝐭 𝐘𝐨𝐮 𝐀𝐫𝐞 𝐆𝐨𝐢𝐧𝐠 𝐭𝐨 𝐀𝐝𝐯𝐞𝐫𝐭𝐢𝐬𝐞:\n\n\\- Look up advertising competitors have used and assess their success.\n\n\\- Understand how consumers think of your kind of products.\n\n\\- Learn the language they use when discussing these products.\n\n\\- Identify which attributes are most important to them.\n\n3. 𝐎𝐧 𝐑𝐞𝐜𝐨𝐠𝐧𝐢𝐳𝐢𝐧𝐠 𝐚 𝐁𝐢𝐠 𝐈𝐝𝐞𝐚 (refers to big ideas such as an advertising angle):\n\n\\- Did it make me gasp when I first saw it?\n\n\\- Do I wish I had thought of it myself?\n\n\\- Does it fit the strategy to perfection?\n\n\\-  Could it be used for 30 years?\n\nI would love to hear if any of you have had any big idea moments and executed them to a successful campaign. That feels like something that many advertisers would dream of having. Ogilvy once read the specifications of Rolls-Royce, and used a line from it as the headline, resulting in a successful campaign.\n\nThat line was: 'At 60 miles an hour the loudest noise in this new Rolls-Royce comes from the electric clock'.",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;&amp;#39;𝐖𝐡𝐞𝐧 𝐲𝐨𝐮 𝐡𝐚𝐯𝐞 𝐰𝐫𝐢𝐭𝐭𝐞𝐧 𝐲𝐨𝐮𝐫 𝐡𝐞𝐚𝐝𝐥𝐢𝐧𝐞, 𝐲𝐨𝐮 𝐡𝐚𝐯𝐞 𝐬𝐩𝐞𝐧𝐭 𝐞𝐢𝐠𝐡𝐭𝐲 𝐜𝐞𝐧𝐭𝐬 𝐨𝐮𝐭 𝐨𝐟 𝐲𝐨𝐮𝐫 𝐝𝐨𝐥𝐥𝐚𝐫&amp;#39; - David Ogilvy&lt;/p&gt;\n\n&lt;p&gt;For context, I&amp;#39;ve been fairly new to the advertising niche, having just fully committed the past year to learning how to run ads regularly on social media platforms. That said, the book nerd in me came up with a list of 50 advertising books to read - and this was the first one I picked up at a local library.&lt;/p&gt;\n\n&lt;p&gt;While I encourage newbies &amp;amp; even experts who could use a refresher to thoroughly read and take notes from the book as the most effective method of learning, here are 3 key takeaways that I now use as a checklist:&lt;/p&gt;\n\n&lt;ol&gt;\n&lt;li&gt;𝐎𝐧 𝐂𝐫𝐚𝐟𝐭𝐢𝐧𝐠 𝐄𝐟𝐟𝐞𝐜𝐭𝐢𝐯𝐞 𝐀𝐝𝐯𝐞𝐫𝐭𝐢𝐬𝐢𝐧𝐠 𝐇𝐞𝐚𝐝𝐥𝐢𝐧𝐞𝐬:&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;p&gt;- The most successful headlines promise a benefit to the reader.&lt;/p&gt;\n\n&lt;p&gt;- Headlines containing news elements are consistently effective.&lt;/p&gt;\n\n&lt;p&gt;- It is advisable to almost always include the brand name in the headline.&lt;/p&gt;\n\n&lt;p&gt;- A headline comprising approximately 10 words tends to have better sales impact.&lt;/p&gt;\n\n&lt;ol&gt;\n&lt;li&gt;𝐎𝐧 𝐒𝐭𝐮𝐝𝐲𝐢𝐧𝐠 𝐭𝐡𝐞 𝐏𝐫𝐨𝐝𝐮𝐜𝐭 𝐘𝐨𝐮 𝐀𝐫𝐞 𝐆𝐨𝐢𝐧𝐠 𝐭𝐨 𝐀𝐝𝐯𝐞𝐫𝐭𝐢𝐬𝐞:&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;p&gt;- Look up advertising competitors have used and assess their success.&lt;/p&gt;\n\n&lt;p&gt;- Understand how consumers think of your kind of products.&lt;/p&gt;\n\n&lt;p&gt;- Learn the language they use when discussing these products.&lt;/p&gt;\n\n&lt;p&gt;- Identify which attributes are most important to them.&lt;/p&gt;\n\n&lt;ol&gt;\n&lt;li&gt;𝐎𝐧 𝐑𝐞𝐜𝐨𝐠𝐧𝐢𝐳𝐢𝐧𝐠 𝐚 𝐁𝐢𝐠 𝐈𝐝𝐞𝐚 (refers to big ideas such as an advertising angle):&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;p&gt;- Did it make me gasp when I first saw it?&lt;/p&gt;\n\n&lt;p&gt;- Do I wish I had thought of it myself?&lt;/p&gt;\n\n&lt;p&gt;- Does it fit the strategy to perfection?&lt;/p&gt;\n\n&lt;p&gt;-  Could it be used for 30 years?&lt;/p&gt;\n\n&lt;p&gt;I would love to hear if any of you have had any big idea moments and executed them to a successful campaign. That feels like something that many advertisers would dream of having. Ogilvy once read the specifications of Rolls-Royce, and used a line from it as the headline, resulting in a successful campaign.&lt;/p&gt;\n\n&lt;p&gt;That line was: &amp;#39;At 60 miles an hour the loudest noise in this new Rolls-Royce comes from the electric clock&amp;#39;.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 0,
  "flair": None,
  "upVotes": 2,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-07T13:57:28.000Z",
  "scrapedAt": "2024-02-10T13:48:27.224Z",
  "dataType": "post"
},
{
  "id": "t3_1akykmq",
  "parsedId": "1akykmq",
  "url": "https://www.reddit.com/r/digital_marketing/comments/1akykmq/any_advice/",
  "username": "Kabikaj",
  "title": "Any advice?",
  "communityName": "r/digital_marketing",
  "parsedCommunityName": "digital_marketing",
  "body": "Our affiliate website has a huge number of PDP pages that are rankly highly for our native region (NL) but are almost always being beaten out to the top spot by a competitor that has less DA than us, worse speed, and exactly the same structured data. I cannot figure out why they're ranking more highly than us. We even have more content than them on the pages, since they just have the product and we have some description text on the page.   \nWe migrated from .nl to .com a couple of years ago, and dropped 50% in traffic before picking back up to where we were before in about 6 months, then in April 2023, we saw a downward trend in traffic and KW rankings after being hit by all of Google's updates. We've since picked back up again, but could these two dips be effecting us negatively in Google's eyes? Is it possible that the competitors beating us to the top spot, although looking worse on paper, are beating us because they've not had major drops in traffic?   \nTrying to research the problem just comes up with a ton of articles on how to rank in SEO, but we've optimised everything we can and they're of no further help.   \nSlightly separately, we're also ranking very poorly in DE and UK/US for our German and English versions of our website, is this likely to be just a case of different search volume competition? Or is it possibly something to do with our /en and /de pages being subdomains of the main .com in Dutch.  \nAny advice would be very much appreciated!   \n",
  "html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Our affiliate website has a huge number of PDP pages that are rankly highly for our native region (NL) but are almost always being beaten out to the top spot by a competitor that has less DA than us, worse speed, and exactly the same structured data. I cannot figure out why they&amp;#39;re ranking more highly than us. We even have more content than them on the pages, since they just have the product and we have some description text on the page.&lt;br/&gt;\nWe migrated from .nl to .com a couple of years ago, and dropped 50% in traffic before picking back up to where we were before in about 6 months, then in April 2023, we saw a downward trend in traffic and KW rankings after being hit by all of Google&amp;#39;s updates. We&amp;#39;ve since picked back up again, but could these two dips be effecting us negatively in Google&amp;#39;s eyes? Is it possible that the competitors beating us to the top spot, although looking worse on paper, are beating us because they&amp;#39;ve not had major drops in traffic?&lt;br/&gt;\nTrying to research the problem just comes up with a ton of articles on how to rank in SEO, but we&amp;#39;ve optimised everything we can and they&amp;#39;re of no further help.&lt;br/&gt;\nSlightly separately, we&amp;#39;re also ranking very poorly in DE and UK/US for our German and English versions of our website, is this likely to be just a case of different search volume competition? Or is it possibly something to do with our /en and /de pages being subdomains of the main .com in Dutch.&lt;br/&gt;\nAny advice would be very much appreciated!   &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
  "numberOfComments": 1,
  "flair": None,
  "upVotes": 3,
  "isVideo": False,
  "isAd": False,
  "over18": False,
  "createdAt": "2024-02-07T08:46:59.000Z",
  "scrapedAt": "2024-02-10T13:48:27.341Z",
  "dataType": "post"
}]